spring:
  application:
    name: tasktracker

  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:8080/tasktracker_java?sslmode=disable
      username: tasktracker_admin
      password: Task@Tracker2026


  sql:
    init:
      data-locations: classpath:db/migration/init.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

